name: "Adam Green"
description: "Adam Green: Physics Graduate Student in Liquid Crystals"

url: "http://localhost:4000"
paginate: 10
markdown: kramdown
remote_theme: no-good-very-bad
permalink: pretty
gems: [jekyll-paginate]

pages_list:
    About: '/about/'
    Archive: '/archive/'
    Physics: '/physics/'
    Contact: '/contact/' 
